//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class datos_prospecto
{
    public int id_datos { get; set; }
    public string calle { get; set; }
    public string numero { get; set; }
    public string colonia { get; set; }
    public Nullable<int> codigo_postal { get; set; }
    public string telefono { get; set; }
    public int id_prospecto { get; set; }

    public virtual prospecto prospecto { get; set; }
}

public partial class documentos
{
    public int id_documento { get; set; }
    public string tipo_documento { get; set; }
    public string documento { get; set; }
    public int id_prospecto { get; set; }

    public virtual prospecto prospecto { get; set; }
}

public partial class prospecto
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public prospecto()
    {
        this.datos_prospecto = new HashSet<datos_prospecto>();
        this.documentos = new HashSet<documentos>();
    }

    public int id_prospecto { get; set; }
    public string nombre { get; set; }
    public string a_paterno { get; set; }
    public string a_materno { get; set; }
    public string rfc { get; set; }
    public Nullable<int> estatus { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<datos_prospecto> datos_prospecto { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<documentos> documentos { get; set; }
}
